### ISSUE TITLE
Assign data to each renamed file?

### ISSUE THREAD

**Issue by lukeed** [lukeed/fly-flatten#1]
Hey @bucaran, would love a quick insight on this one.

Each file gets renamed within `this.unwrap()`.

What needs to happen next is either:
1. replace each `file` name with the new name, or
2. read the `Buffer` data-stream from the original file path, then store that data with the new name into an object 

I started to do #2 [here](https://github.com/lukeed/fly-flatten/blob/master/index.js#L15), but then how would you pass that new object into `target()`?

This was the issue I ran into with [fly-rev](https://github.com/lukeed/fly-rev) too, but it was _ok_ to have it act as an endpoint in that instance.

**Comment by lukeed** [comment]
...This is also why I'm working on a new plugin system :laughing:. I find it to be extremely hit-or-miss / clunky when creating plugins, **unless** a library you're implementing exposes an API that can be deferred or used as a callback, which 97% of the current Fly plugins happen to do.

**Comment by ghost** [comment]
My understanding must be _wrong_ I guess, because I thought that:

``` js
const src = ['app/images/**/*.{jpg,png,gif}']
```

would expand to all the files inside `target` when running `yield expand`..., so effectively we end up with a flat list of all the files already and `target('dist/img')` should do what this plugin is trying to do.

Don't you think Fly should do this out of the box?

**Comment by lukeed** [comment]
Well, its behavior behavior is close, but not quite right / what's expected.

Given this file structure:

```
app
|- \images
  |- img-1.jpg
  |- img-2.jpg
  |- \one
    |- one-1.jpg
    |- one-2.jpg
    |- \two
      |- two-1.jpg
      |- two-2.jpg
```

.. and given a raw `yield this.source(src).target('dist/img');`, the following occurs:

**Test:**

``` js
src = ['app/images/**/*.jpg']
```

**Results:**

```
dist
|- \img
  |- img-1.jpg
  |- img-2.jpg
  |- \one
    |- one-1.jpg
    |- one-2.jpg
    |- \two
      |- two-1.jpg
      |- two-2.jpg
```

It copies the entire structure from the **last specified** directory, in this case, `app/images`.

**Expected "0"** (with `.flatten({ levels: 0 })`):

```
dist
|- \img
 |- img-1.jpg
 |- img-2.jpg
 |- one-1.jpg
 |- one-2.jpg
 |- two-1.jpg
 |- two-2.jpg
```

**Expected "1"** (with `.flatten({ levels: 1 })`):

```
dist
  |- \img
  |- img-1.jpg
  |- img-2.jpg
  |- \one
    |- one-1.jpg
    |- one-2.jpg
  |- \two
    |- two-1.jpg
    |- two-2.jpg
```

This means that it retains 1 parent-level, and nests that in the destination.

Now, in order to matched the "Expected 0", this is what the source must be:

``` js
yield this
  .source([
    'app/images/*.jpg',
    'app/images/one/*.jpg',
    'app/images/one/two/*.jpg',
  ])
  .target('dist/img');
```

Notice that there are no recursive directory globs -- just a bunch of shallow file selections. This works because of the point I mentioned earlier, Fly globs listen to the _last specified_ directory.

And, as you can imagine, this gets to be **really** nasty when you start dealing with lots and lots of subdirectories. Similar issues found [here](https://github.com/bucaran/fly/issues/107) and [here](https://github.com/bucaran/fly/issues/103).

This plugin (or core feature?) would make all glob selections work flawlessly, and even allow `app/images/**/*` to work, too. (This currently results in "EISDIR: illegal read operation on a directory")

Finally, is this _were_ to be a core patch, then this'll knock [this](https://github.com/bucaran/fly/issues/91) off the list too. :wink:

**Comment by ghost** [comment]
Oh, that's right! I recall now and you are right, that's the current behavior, but I have a feeling that what this plugin is trying to accomplish, to `flatten` the directory structure was actually the _original_ behavior_, which is funny, but I might be wrong.

Anyhow, if I am not mistaken, the bit responsible for this and the part where a change would be required to make creating this plugin easier is probably here:

https://github.com/bucaran/fly/blob/master/src/fly.js#L173

**Comment by lukeed** [comment]
Lol, I'll take that as a "forget the plugin, needs to be core"

In that case, I'll work it in as a second, optional parameter to target.

**Comment by ghost** [comment]
We definitely want to keep Fly as simple as possible so I see where you were going at with fly-flatten, but on the other hand, this _smells_ like core to me.

**Comment by lukeed** [comment]
Yea, split as well. But I'll give it a go (tonight maybe) and you can be the final judge.

**Comment by lukeed** [comment]
Incorporated into core -- see [Fly PR](https://github.com/bucaran/fly/pull/135).
